// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

function reasonMessage(param) {
  return "from compiled ReasonML via ParcelJS on Cloud Functions!";
}

export { reasonMessage };
/* No side effect */
